In [119]:
#Shock tube assignment. Code written by Shantanu Bailoor

import numpy as np

#Define grid parameters
#Spatial grid
xmin = -10.0;
xmax = 10.0;
nx = 200;
x = np.linspace(xmin,xmax,nx);
dx = (xmax - xmin)/(nx-1);

#Temporal grid
Tmin = 0.0;
Tmax = 10.0;
dt = 0.01;

#nt = int((Tmax-Tmin)/dt) + 1
nt = 1

#problem parameters
gam  = 1.4;
u    = np.zeros((nx,3));
unew = np.zeros((nx,3));
u0   = np.zeros((nx,3));
uplt = np.zeros((nx,3,nt));

def init_u(u0):
    for i in range (nx):
        if (x[i] < 0.0):
            u0[i] = [1.0, 0.0, 100.0/(gam-1.0)]
        elif (x[i] > 0.0):
            u0[i] = [0.125, 0.0, 10.0/(gam-1.0)]
            
#Compute flux vector
def computeF(uin):
    Fv = np.zeros((nx,3));
    print(uin[nx-1]);
    for i in range (nx):
        rho =  uin[i][0];
        rhou = uin[i][1];
        rhoe = uin[i][2];

        rhou2 = rhou**2/rho;
        
        print(i);
        print(uin[i]); 
        print(rho);
        print(rhou);
        print(rhoe);
        print('');
        p = (gam-1)*(rhoe - 0.5*rhou2);

        #Define flux vector:
        Fv[i] = [rhou, (rhou2 + p), ((rhoe + p)*rhou/rho)];
    print(uin[nx-1]);    
    return Fv;
            
#Richtmeyer time-stepping scheme
def Richtmeyer(u, nplt):
    usr  = np.zeros((nx,3));
    Fsr  = np.zeros((nx,3));
    
    F = computeF(u);
    
    for i in range (0,nx-1):
        usr[i] = 0.5*(np.array(u[i]) + np.array(u[i+1])) - \
        0.5*dt/dx*(np.array(F[i+1]) - np.array(F[i]));
        
    Fsr = computeF(usr);
    unew[1:] = u[1:] -dt/dx*(Fsr[1:]-Fsr[:-1]);
    u = np.copy(unew);
    #uplt[:][:][nplt] = np.copy(unew); 

#Initialize the solution vector            
init_u(u0);
u = np.copy(u0);

computeF(u0);
time = Tmin

#Start time marching
for n in range(nt):
    Richtmeyer(u, n);
    time = time + dt;

[  0.125   0.     25.   ]
0
[   1.    0.  250.]
1.0
0.0
250.0

1
[   1.    0.  250.]
1.0
0.0
250.0

2
[   1.    0.  250.]
1.0
0.0
250.0

3
[   1.    0.  250.]
1.0
0.0
250.0

4
[   1.    0.  250.]
1.0
0.0
250.0

5
[   1.    0.  250.]
1.0
0.0
250.0

6
[   1.    0.  250.]
1.0
0.0
250.0

7
[   1.    0.  250.]
1.0
0.0
250.0

8
[   1.    0.  250.]
1.0
0.0
250.0

9
[   1.    0.  250.]
1.0
0.0
250.0

10
[   1.    0.  250.]
1.0
0.0
250.0

11
[   1.    0.  250.]
1.0
0.0
250.0

12
[   1.    0.  250.]
1.0
0.0
250.0

13
[   1.    0.  250.]
1.0
0.0
250.0

14
[   1.    0.  250.]
1.0
0.0
250.0

15
[   1.    0.  250.]
1.0
0.0
250.0

16
[   1.    0.  250.]
1.0
0.0
250.0

17
[   1.    0.  250.]
1.0
0.0
250.0

18
[   1.    0.  250.]
1.0
0.0
250.0

19
[   1.    0.  250.]
1.0
0.0
250.0

20
[   1.    0.  250.]
1.0
0.0
250.0

21
[   1.    0.  250.]
1.0
0.0
250.0

22
[   1.    0.  250.]
1.0
0.0
250.0

23
[   1.    0.  250.]
1.0
0.0
250.0

24
[   1.    0.  250.]
1.0
0.0
250.0

25
[   1.    0.  250.]
1.0
0.0
250

/home/gil/anaconda3/lib/python3.4/site-packages/IPython/kernel/__main__.py:46: RuntimeWarning: invalid value encountered in double_scalars
